"""Typed state definition for LangGraph state graph transitions."""

from typing import List, Dict, Any, Optional, Annotated
from typing_extensions import TypedDict
import operator


class AgentState(TypedDict):
    """Strongly typed state dictionary passed across LangGraph nodes.

    Attributes:
        query: User input prompt string.
        messages: Chat history messages list.
        intent: Classified route intent ('rag', 'sql', or 'unknown').
        retrieved_docs: Document context payloads retrieved from Qdrant.
        sql_query: Generated SQL statement string.
        sql_result: DB query execution results.
        final_response: Formatted final answer generated by Gemini API.
        error: Optional error string message.
    """

    query: str
    messages: Annotated[List[Dict[str, Any]], operator.add]
    intent: Optional[str]
    retrieved_docs: List[Dict[str, Any]]
    sql_query: Optional[str]
    sql_result: Optional[List[Dict[str, Any]]]
    final_response: Optional[str]
    error: Optional[str]
