"""Typed state definition for LangGraph state graph transitions."""

import operator
from typing import Annotated, Any

from typing_extensions import TypedDict


class AgentState(TypedDict):
    """Strongly typed state dictionary passed across LangGraph nodes.

    Attributes:
        query: User input prompt string.
        messages: Chat history messages list.
        intent: Classified route intent ('rag', 'sql', or 'unknown').
        retrieved_docs: Document context payloads retrieved from Qdrant.
        sql_query: Generated SQL statement string.
        sql_result: DB query execution results.
        final_response: Formatted final answer generated by Gemini API.
        error: Optional error string message.
    """

    query: str
    messages: Annotated[list[dict[str, Any]], operator.add]
    intent: str | None
    retrieved_docs: list[dict[str, Any]]
    sql_query: str | None
    sql_result: list[dict[str, Any]] | None
    final_response: str | None
    error: str | None
